export const GET_LISTS = 'GET_LIST';

export const GET_LISTS_DRIVER = 'GET_LIST_DRIVER';
export const GET_DETAIL_DRIVER = 'GET_DRIVER';
export const CREATE_DRIVER = 'CREATE_DRIVER';
export const UPDATE_DRIVER = 'UPDATE_DRIVER';
export const DELETE_DRIVER = 'DELETE_DRIVER';


export const GET_LISTS_TRUCK = 'GET_LIST_TRUCK';
export const GET_DETAIL_TRUCK = 'GET_DRIVER';
export const CREATE_TRUCK = 'CREATE_TRUCK';
export const UPDATE_TRUCK = 'UPDATE_TRUCK';
export const DELETE_TRUCK = 'DELETE_TRUCK';

export const GET_LISTS_SHIPMENT = 'GET_LIST_SHIPMENT';
export const GET_DETAIL_SHIPMENT = 'GET_DRIVER';
export const CREATE_SHIPMENT = 'CREATE_SHIPMENT';
export const UPDATE_SHIPMENT = 'UPDATE_SHIPMENT';
export const DELETE_SHIPMENT = 'DELETE_SHIPMENT';

export const GET_LISTS_ASSIGN_SHIPMENT = 'GET_LIST_ASSIGN_SHIPMENT';
export const CREATE_ASSIGN_SHIPMENT = 'CREATE_ASSIGN_SHIPMENT';
export const UPDATE_ASSIGN_SHIPMENT = 'UPDATE_ASSIGN_SHIPMENT';
export const DELETE_ASSIGN_SHIPMENT = 'DELETE_ASSIGN_SHIPMENT';

export const GET_LISTS_ASSIGNED_SHIPMENT = 'GET_LIST_ASSIGNED_SHIPMENT';
export const CREATE_ASSIGNED_SHIPMENT = 'CREATE_ASSIGNED_SHIPMENT';
export const UPDATE_ASSIGNED_SHIPMENT = 'UPDATE_ASSIGNED_SHIPMENT';
export const DELETE_ASSIGNED_SHIPMENT = 'DELETE_ASSIGNED_SHIPMENT';


